<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IsExternalInit" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\MERX\MERX\References\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\MERX\MERX\References\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CommandSystem.Core">
      <HintPath>E:\Dependencies\CommandSystem.Core.dll</HintPath>
    </Reference>
    <Reference Include="LabApi">
      <HintPath>..\..\MERX\MERX\References\LabApi.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>E:\Dependencies\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\MERX\MERX\References\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\MERX\MERX\References\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
	  <Publicize Include="Mirror" />
  </ItemGroup>

</Project>
